const data = {
  products: [
    {
      name: "Lampadaire BLAKE",
      slug: "lampadaire-blake",
      category: "Decoration",
      price: "129",
      image: "/images/lamp1.png",
      rating: 3,
      reviews: 1209,
      stock: 20,
      description:
        "Lampadaire avec abat-jour en métal et piètement bois - BLAKE",
    },
    {
      name: "Meuble de rangement",
      slug: "meuble-de-rangement",
      category: "Cupboard",
      image: "/images/rangement2.png",
      price: "90",
      rating: 4,
      reviews: 504,
      stock: 7,
      description:
        "Vous aimez le style ? La combinaison harmonieuse de panneaux d’aggloméré marron rustique et d’un cadre en métal noir donne vie à ce meuble de un style industriel.",
    },
    {
      name: "Fauteuil Bleu Marine",
      slug: "fauteuil-bleu-marine",
      category: "Bed and Armchair",
      image: "/images/fauteuil1.png",
      price: "189",
      rating: 4.5,
      reviews: 704,
      stock: 10,
      description:
        "Confortable, design et intelligent, votre fauteuil vous promet des moments de détente absolue grâce aux nombreuses options disponibles telles que la fonction massage, le siège chauffant ou un support lombaire",
    },
    {
      name: "Lampadaire BLAKE",
      slug: "lampadaire-blake",
      category: "Decoration",
      image: "/images/lamp1.png",
      price: "129",
      rating: 4.5,
      reviews: 1209,
      stock: 20,
      description:
        "Lampadaire avec abat-jour en métal et piètement bois - BLAKE",
    },
  ],
  plants: [
    {
      name: "plante verte",
      slug: "plante-verte",
      category: "Plantes",
      image: "/images/plante-verte.jpg",
      price: "79",
      rating: 4.5,
      reviews: 704,
      stock: 10,
      description: "Plante en pot, 24 cm ",
    },
    {
      name: "plante verte",
      slug: "plante-verte",
      category: "Plantes",
      image: "/images/plante-verte.jpg",
      price: "79",
      rating: 4,
      reviews: 704,
      stock: 10,
      description: "Plante en pot, 24 cm ",
    },
    {
      name: "plante verte",
      slug: "plante2",
      category: "Plantes",
      image: "/images/plante2.png",
      price: "79",
      rating: 3.5,
      reviews: 704,
      stock: 10,
      description: "Plante en pot, 24 cm",
    },
    {
      name: "plante verte",
      slug: "plante-verte",
      category: "Plantes",
      image: "/images/plante-verte.jpg",
      price: "79",
      rating: 4.5,
      reviews: 704,
      stock: 10,
      description: "Plante en pot, 24 cm ",
    },
  ],
  categories: [
    {
      name: "Cupboard",
      image: "/images/cupboard.png",
    },
    {
      name: "Bathroom",
      image: "/images/cat-bain.png",
    },
    {
      name: "Decoration",
      image: "/images/cat-deco.png",
    },
    {
      name: "Bed and Mattress",
      image: "/images/cat-lit.png",
    },
  ],
  bathrooms: [
    {
      name: "lavabo",
      slug: "Lavabo",
      category: "Bathroom",
      image: "/images/cat-bain.png",
      price: "99",
      rating: 4.5,
      reviews: 704,
      stock: 10,
      description: "Votre salle de bain ne sera jamais si belle ",
    },
    {
      name: "lavabo",
      slug: "Lavabo",
      category: "Bathroom",
      image: "/images/cat-bain.png",
      price: "99",
      rating: 4.5,
      reviews: 704,
      stock: 10,
      description: "Votre salle de bain ne sera jamais si belle ",
    },
    {
      name: "lavabo",
      slug: "Lavabo",
      category: "Bathroom",
      image: "/images/cat-bain.png",
      price: "99",
      rating: 4.5,
      reviews: 704,
      stock: 10,
      description: "Votre salle de bain ne sera jamais si belle ",
    },
    {
      name: "lavabo",
      slug: "Lavabo",
      category: "Bathroom",
      image: "/images/cat-bain.png",
      price: "99",
      rating: 4.5,
      reviews: 704,
      stock: 10,
      description: "Votre salle de bain ne sera jamais si belle ",
    },
  ],
};

export default data;
